# Generated by Django 4.1.7 on 2023-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0003_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="non_reimbursable",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
