# Generated by Django 4.1.7 on 2023-05-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0004_doctor_non_reimbursable"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                ("from_hour", models.TimeField()),
                ("to_hour", models.TimeField()),
                ("lunch_hour", models.TimeField(blank=True, null=True)),
                ("lunch_end_hour", models.TimeField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medicus.doctor"
                    ),
                ),
            ],
            options={
                "unique_together": {("doctor", "weekday")},
            },
        ),
    ]
