# Generated by Django 4.1.7 on 2023-05-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0006_rename_openinghours_openinghour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghour",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_hours",
                to="medicus.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="openinghour",
            name="weekday",
            field=models.IntegerField(
                choices=[
                    (1, "월요일"),
                    (2, "화요일"),
                    (3, "수요일"),
                    (4, "목요일"),
                    (5, "금요일"),
                    (6, "토요일"),
                    (7, "일요일"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("expiration", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apointments",
                        to="medicus.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicus.patient",
                    ),
                ),
            ],
        ),
    ]
