# Generated by Django 4.1.7 on 2023-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0007_alter_openinghour_doctor_alter_openinghour_weekday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="consultation_hour",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
