# Generated by Django 4.1.7 on 2023-05-08 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0008_appointment_consultation_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="consultation_hour",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
