# Generated by Django 4.1.7 on 2023-05-08 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicus", "0009_alter_appointment_consultation_hour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="consultation_hour",
            new_name="consultation_datetime",
        ),
    ]
